project_id = "vmhpmgiozhfzkzymvmaq"

[functions.reset-admin-password]
verify_jwt = false

[functions.create-mercadopago-payment]
verify_jwt = false

[functions.update-product-from-hubjoias]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.send-customer-email]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.test-payment-update]
verify_jwt = false
