// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmhpmgiozhfzkzymvmaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtaHBtZ2lvemhmemt6eW12bWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NTM0ODAsImV4cCI6MjA3MzAyOTQ4MH0.lybFy8ZuoCgWblJRMSgKonDBilG-t5aLt9xPA9yEo-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});